version: '3'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - database
      - email
    volumes:
      - .:/opt/flask/blog
  database:
    image: percona:5.7.20
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=blog
      - MYSQL_USER=database_blog_user
      - MYSQL_PASSWORD=database_blog_user_password
    ports:
      - "3306:3306"
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_bin
  email:
    image: catatnight/postfix
    environment:
      - maildomain=mail.example.com
      - smtp_user=relay@mail.example.com:relay