# https://dev.mysql.com/doc/refman/5.7/en/glossary.html#glos_schema
# "In MySQL a schema is synonymous with a database"
sqlalchemy:
  schema: 'blog'
  hostname: 'database'
  username: 'database_blog_user' 
  password: 'database_blog_user_password'
  driver: 'mysql pymysql'
