"""empty message

Revision ID: 5a7e22b3c23e
Revises: 9e4ec67c0bb3
Create Date: 2018-02-20 07:00:02.664811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a7e22b3c23e'
down_revision = '9e4ec67c0bb3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('created', sa.DateTime(), nullable=False))
    op.add_column('users', sa.Column('last_modified', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_modified')
    op.drop_column('users', 'created')
    # ### end Alembic commands ###
